name: Slapper
author: jojoe77777
version: 1.4.0
description:
main: slapper\Main
api: [3.0.0]

commands:
  slapper:
    description:
    usage: "/slapper [args]"
    permission: slapper.command
  rca:
    description:
    usage: "/rca <player> <command>"
    permission: slapper.rca
  nothing:
    description:
    usage: "/nothing"
    permission: slapper.nothing

permissions:
  slapper:
    description:
    default: op
    children:
      slapper.command:
        description:
        default: op
      slapper.create:
        description:
        default: op
      slapper.edit:
        description:
        default: op
      slapper.nothing:
        description:
        default: op
      slapper.rca:
        description:
        default: op
      slapper.remove:
        description:
        default: op
      slapper.id:
        description:
        default: op
      slapper.help:
        description:
        default: op
